### ISSUE TITLE
[BUG] OTL 앱 출시 배너가 계속 표시됨

### ISSUE THREAD

**Issue by yumincho** [sparcs-kaist/otlplus-web#76]
## 설명 \*

OTL 앱 출시 배너가 "다시 보지 않기"를 선택해도 계속 다시 표시됩니다. 더이상 배너가 표시되지 않도록 **배너를 제거**합니다.

## 테스트 환경 \*

- Web Version: [e.g. 1.1.0]

## 에러 로그

```sh
(OPTIONAL)
```

**Comment by UrWrstNightmare** [comment]
issue resolved in #80
